
events {
    worker_connections 1024;
}
 
http {
    client_max_body_size 1M;
 
    server {
        listen 127.0.0.1:8080;
        server_name localhost;
        root ./server_main_dir;
        index index.html;
        timeout 60;
 
        location / {
            allowed_methods GET;
            autoindex off;
            index index.html;
            return 301;
        }
    }
}