http {
    # Global settings
    client_max_body_size 1.9g; #0.93 GB

    # Error pages (relative to server root directory)
    error_page 400 ./www/html/errors/400.html;
    error_page 401 ./www/html/errors/401.html;
    error_page 403 ./www/html/errors/403.html;
    error_page 404 ./www/html/errors/404.html;
    error_page 405 ./www/html/errors/405.html;
    error_page 408 ./www/html/errors/408.html;
    error_page 411 ./www/html/errors/411.html;
    error_page 413 ./www/html/errors/413.html;
    error_page 500 ./www/html/errors/500.html;
    error_page 502 ./www/html/errors/502.html;
    error_page 503 ./www/html/errors/503.html;
    error_page 504 ./www/html/errors/504.html;

    server {
        listen localhost:8080;
        server_name example.com;

        root ./www/html;
        index index.html;
        timeout 60;

        # === ROOT LOCATION ===
        location / {
            allowed_methods GET POST DELETE;
            autoindex off;
        }

        # === DASHBOARD ===
        location /dashboard/ {
            allowed_methods GET;
            index index.html;
            autoindex off;
        }

        # === CGI BIN ===
        location /cgi-bin/ {
            client_max_body_size 111m; # 1mb
            allowed_methods GET POST;
            cgi_path /usr/bin/python3 /usr/bin/bash;
            cgi_ext .py .sh;
        }

        # === REDIRECTS ===
        location /redirect/ {
            allowed_methods GET;
            return 301 /new-page.html;
        }

        # === UPLOADS ===
        location /uploads/ {
            client_max_body_size 1.9g; # 1mb
            allowed_methods GET POST DELETE;
            upload_path ./www/html/uploads/;
            autoindex on;
        }

        # === ERROR PAGES DIRECTORY ===
        location /errors/ {
            allowed_methods GET;
            autoindex off;
        }
    }

}
