http {
    # Global settings
    client_max_body_size 999999999; 

    # Error pages (Absolute paths)
    error_page 400 /goinfre/fbenalla/for_push/www/html/errors/400.html;
    error_page 401 /goinfre/fbenalla/for_push/www/html/errors/401.html;
    error_page 403 /goinfre/fbenalla/for_push/www/html/errors/403.html;
    error_page 404 /goinfre/fbenalla/for_push/www/html/errors/404.html;
    error_page 405 /goinfre/fbenalla/for_push/www/html/errors/405.html;
    error_page 408 /goinfre/fbenalla/for_push/www/html/errors/408.html;
    error_page 411 /goinfre/fbenalla/for_push/www/html/errors/411.html;
    error_page 413 /goinfre/fbenalla/for_push/www/html/errors/413.html;
    error_page 500 /goinfre/fbenalla/for_push/www/html/errors/500.html;
    error_page 502 /goinfre/fbenalla/for_push/www/html/errors/502.html;
    error_page 503 /goinfre/fbenalla/for_push/www/html/errors/503.html;
    error_page 504 /goinfre/fbenalla/for_push/www/html/errors/504.html;

    server {
        listen 127.0.0.1:8080;
        server_name fahd.com;

        # Absolute Root mapping
        root /goinfre/fbenalla/for_push/www/html;
        index index.html;
        timeout 8;

        location / {
            allowed_methods GET DELETE;
            autoindex off;
        }

        location /dashboard/ {
            allowed_methods GET;
            index index.html; 
            autoindex on;
        }

        # === CGI BIN ===
        location /cgi-bin/ {
            client_max_body_size 111m;
            allowed_methods GET POST;
            cgi_path /usr/bin/python3 /usr/bin/bash;
            cgi_ext .py .sh;
        }

        # === UPLOADS ===
        location /uploads/ {
            client_max_body_size 1111m; 
            allowed_methods GET POST ;
            upload_path /goinfre/fbenalla/for_push/www/html/uploads/;
            autoindex on;
        }

        location /errors/ {
            allowed_methods GET;
            autoindex off;
        }
    }
}