http {
    # Global settings
    client_max_body_size 1.9G;

    error_page 400 ./www/html/errors/400.html;## Error pages (relative to server root directory)
    
    error_page 401 ./www/html/errors/401.html;
    error_page 403 ./www/html/errors/403.html;
    error_page 404 ./www/html/errors/404.html;
    error_page 404 "/errors/#not_found.html";
    error_page 405 ./www/html/errors/405.html;
    error_page 408 ./www/html/errors/408.html;
    error_page 411 ./www/html/errors/411.html;
    error_page 413 ./www/html/errors/413.html;
    error_page 500 ./www/html/errors/500.html;
    error_page 502 ./www/html/errors/502.html;
    error_page 503 ./www/html/errors/503.html;
    error_page 504 ./www/html/errors/504.html;

    server {
        listen 8080;
        server_name fahd.com;

        root ./www/html;
        index index.html;
        timeout 80;

    }

}