events {
    # Though the subject forces a specific I/O model (single poll/select),
    # you can define max simultaneous connections here for resource management.
    worker_connections 1024;
    event_model select;
}

http {
    # Global HTTP settings (Inherited by all servers)
    client_max_body_size 10M;          # Mandatory 1G is the max 
    error_page 404 401 402 ./errors/404.html;   # Mandatory 
    
    server {
        listen 127.0.0.1:8080;
        server_name localhost webserv.test;
        root        ./server_main_dir;
        index       index.html;
        timeout     60;
        client_max_body_size 10M;          # Mandatory 1G is the max 

        error_page 404 /errors/404.html;
        error_page 500 /errors/500.html;

        location / {
            client_max_body_size 10M;          # Mandatory 1G is the max 

            allowed_methods GET POST;
            autoindex       off;
            index           index.html;
        }

        location /autoindex_test/ {
            allowed_methods GET;
            autoindex       on;
        }

        location /cgi-bin/ {
            allowed_methods GET POST;
            cgi_ext   .py;
            cgi_path        /usr/bin/python3;
        }

        location /uploads/ {
            allowed_methods POST;
            client_max_body_size 5M;          # Mandatory 1G is the max 

            upload_path     ./server_main_dir/uploads/;
        }

        location /old-page {
            return 301 /index.html;      # HTTP Redirection 
        }
    }
}