events {
    worker_connections 1024;
    event_model select;
}

http {
    client_max_body_size 10M;

    server {
        listen 10.11.5.12:8181;
        server_name localhost;

        root /goinfre/jbahmida/plyr/demo;
        index index.html;
        timeout 60;
        client_max_body_size 10M;

        error_page 404 /errors/404.html;
        error_page 500 /errors/500.html;

        location / {
            allowed_methods GET POST DELETE;
            autoindex on;
            index index.html;
            client_max_body_size 10M;
        }

        location /autoindex_test/ {
            allowed_methods GET ;
            autoindex on;
        }

        location /cgi-bin/ {
            allowed_methods GET  POST;
            cgi_ext .py;
            cgi_path /usr/bin/python3;
        }

        location /uploads/ {
            allowed_methods GET  POST DELETE;
            client_max_body_size 5M;
            upload_path /goinfre/jbahmida/server_main_dir/uploads;
            autoindex on;
        }

        location /old-page {
            return 301 /errors/500.html;
        }
    }
}