http {
    client_max_body_size 100M;

    server {
        listen 8080;
        server_name fahd8080.com;

        root ./www/html;
        index index.html;
        timeout 80;
    }

    server {
        listen 8080;
        server_name fahd8081.com;

        root ./www/html;
        index index.html;
        timeout 80;
    }

    server {
        listen 8080;
        server_name fahd8082.com;

        root ./www/html;
        index index.html;
        timeout 80;
    }

    server {
        listen 8080;
        server_name fahd8083.com;

        root ./www/html;
        index index.html;
        timeout 80;
    }

    server {
        listen 8080;
        server_name fahd8084.com;

        root ./www/html;
        index index.html;
        timeout 80;
    }

    server {
        listen 8080;
        server_name fahd8085.com;

        root ./www/html;
        index index.html;
        timeout 80;
    }

    server {
        listen 8080;
        server_name fahd8086.com;

        root ./www/html;
        index index.html;
        timeout 80;
    }

    server {
        listen 8080;
        server_name fahd8087.com;

        root ./www/html;
        index index.html;
        timeout 80;
    }

    server {
        listen 8080;
        server_name fahd8088.com;

        root ./www/html;
        index index.html;
        timeout 80;
    }

    server {
        listen 8080;
        server_name fahd8089.com;

        root ./www/html;
        index index.html;
        timeout 80;
    }

    server {
        listen 8080;
        server_name fahd8090.com;

        root ./www/html;
        index index.html;
        timeout 80;
    }

    server {
        listen 8080;
        server_name fahd8091.com;

        root ./www/html;
        index index.html;
        timeout 80;
    }

    server {
        listen 8080;
        server_name fahd8092.com;

        root ./www/html;
        index index.html;
        timeout 80;
    }

    server {
        listen 8080;
        server_name fahd8093.com;

        root ./www/html;
        index index.html;
        timeout 80;
    }

    server {
        listen 8080;
        server_name fahd8094.com;

        root ./www/html;
        index index.html;
        timeout 80;
    }

    server {
        listen 8080;
        server_name fahd8095.com;

        root ./www/html;
        index index.html;
        timeout 80;
    }

    server {
        listen 8080;
        server_name fahd8096.com;

        root ./www/html;
        index index.html;
        timeout 80;
    }

    server {
        listen 8080;
        server_name fahd8097.com;

        root ./www/html;
        index index.html;
        timeout 80;
    }

    server {
        listen 8080;
        server_name fahd8098.com;

        root ./www/html;
        index index.html;
        timeout 80;
    }

    server {
        listen 8080;
        server_name fahd8099.com;

        root ./www/html;
        index index.html;
        timeout 80;
    }
    # server {
    #     listen 8080;
    #     server_name fahd8010.com;

    #     root ./www/html;
    #     index index.html;
    #     timeout 80;
    # }
    # server {
    #     listen 8080;
    #     server_name fahd80102.com;

    #     root ./www/html;
    #     index index.html;
    #     timeout 80;
    # }
}
