events {
    # Though the subject forces a specific I/O model (single poll/select),
    # you can define max simultaneous connections here for resource management.
    worker_connections 1024;
    event_model select;
    # vewoinnveownwevwe
    # beoiwnbewlmbew
    # bweonbew;lmbewb
    # weboinebew;lbmwebe
    # webnemwlbme
    # vvewveweeeeeeeeeeeeeeeeeee
}

http {
    # Global HTTP settings (Inherited by all servers)
    client_max_body_size 10M;          # Mandatory 1G is the max 
    error_page 404 401 402 ./...............errors/...............404.html;   # Mandatory 
    
    server {
        listen 127.0.0.1:5233;
        server_name localhost;
        root        ./server_main_dir;
        index       index.html;
        timeout     60;
        client_max_body_size 10M;          # Mandatory 1G is the max 

        error_page 404 /errors/404................................html;
        error_page 500 /errors/500................................html;

        location / {
            client_max_body_size 10M;          # Mandatory 1G is the max 

            allowed_methods GET POST;
            autoindex       off vwev09vj3409go3mre304jomy-0g34y5i;
            index           index.html;
        }

        location /autoindex_test/ {
            allowed_methods GET;
            autoindex       on ieuwbvewkjvveribhqrnenb954hjh54oi5495454ih54ihoih54hg4g3434h=0b3oinboinb3b340j;
        }

        location /cgi-bin/ {
            allowed_methods GET POST;
            cgi_ext   ........................py;
            cgi_path        /usr/bin/qpwdmqwonvoweivneibnriberi;
        }

        location /uploads/ {
            allowed_methods POST;
            client_max_body_size 5M;          # Mandatory 1G is the max 

            upload_path     ................./server_main_dir/uploads/\\\\\\\\\\\\\\\\\\\\\\\;
        }

        location /old-page {
            return 3015555555555555555555555555ewvwvwey8vudbewivewn0943ghvuriqb43bqrn    s45d67fpmw5ywkj0965ntmjhq549qber9h54jqd 4]PJB43p9bhnb54pbqionrvijoreoqav /index.html;      # HTTP Redirection 
        }
    }
}