# #Youpi

http {

    client_max_body_size 999M;

    server {
        
        client_max_body_size 999M;

        listen 5500;
        server_name localhost;
        timeout 80;
        

        root ./;
        index index.html;

        location / {
            allowed_methods GET;
            autoindex on;
        }

        location /post_body {
            allowed_methods POST;
            upload_path  ./post_body;
            client_max_body_size 100;
        }

        location /directory/ {
            client_max_body_size 999M;

            allowed_methods GET;
            index youpi.bad_extension;
        }

        location /directory/youpi.bla {
            allowed_methods GET POST;
            root ./directory;
            cgi_path ./cgi_test; # both tested succefuly ms zid testiha
            # cgi_path /tmp/cgi_test;
            cgi_ext .bla;
            client_max_body_size 100M;
        }

        location /directory/youpla.bla {
            allowed_methods GET POST;
            root ./directory;
            cgi_path ./cgi_test;
            # cgi_path /tmp/cgi_test;
            cgi_ext .bla;
            client_max_body_size 999M;
        }

    }

}