events {
    worker_connections 1;
    event_model epoll;
}

http {
    client_max_body_size 1M;
    server {
        listen 127.0.0.1:8080;
        server_name ret-bad.local;
        root ./www/html;
        index index.html;
        timeout 10;

        location /old/ {
            return 200 /new/;
        }
    }
}
