events {
    worker_connections 2;
    event_model epoll;
}

http {
    client_max_body_size 16M;

    server {
        listen 127.0.0.1:8081;
        server_name redir.local;
        root ./www/html;
        index index.html;
        timeout 15;

        location /old/ {
            return 301 /new/;
        }

        location / {
            allowed_methods GET;
        }
    }
}
