events {
    worker_connections 16;
    event_model epoll;
}

http {
    client_max_body_size 32M;
    server {
        listen 127.0.0.1:8085;
        server_name stress.local;
        root ./www/html;
        index index.html;
        timeout 120;

        location / { allowed_methods GET; }
        location /a/ { allowed_methods GET; }
        location /a/b/ { allowed_methods GET; }
        location /a/b/c/ { allowed_methods GET; }
        location /api/ { allowed_methods GET POST; }
        location /api/v1/ { allowed_methods GET POST; }
        location /api/v1/users/ { allowed_methods GET POST; }
        location /uploads/ { allowed_methods POST; upload_path ./www/uploads/; }
        location /cgi-bin/ { allowed_methods GET POST; cgi_ext .py; cgi_path /usr/bin/python3; }
        location /static/ { allowed_methods GET; }
        location /assets/ { allowed_methods GET; }
        location /assets/img/ { allowed_methods GET; }
    }
}
