events {
    worker_connections 4;
    event_model epoll;
}

http {
    client_max_body_size 8M;
    error_page 404 ./errors/404.html;
    error_page 500 ./errors/500.html;

    server {
        listen 127.0.0.1:8080;
        server_name app.local www.app.local;
        root ./www/html;
        index index.html;
        timeout 45;

        location / {
            allowed_methods GET POST;
            index index.html;
        }

        location /cgi-bin/ {
            allowed_methods GET POST;
            cgi_ext .py;
            cgi_path /usr/bin/python3;
        }

        location /uploads/ {
            allowed_methods POST;
            upload_path ./www/uploads/;
        }
    }

    server {
        listen 127.0.0.1:9090;
        server_name api.local;
        root ./www/api;
        index index.html;
        timeout 30;

        location /v1/ {
            allowed_methods GET;
        }
    }
}
