# Global/Main Context

events {
    # Though the subject forces a specific I/O model (single poll/select),
    # you can define max simultaneous connections here for resource management.
    worker_connections 1;
    event_model select;
}

http {
    # Global HTTP settings (Inherited by all servers)
    client_max_body_size 10M;          # Mandatory 
    client_max_body_size 20M;          # Mandatory 
    error_page 404 401 402 ./errors/404.html;   # Mandatory 
    
    server {
        listen 127.0.0.1:8080;                   # Mandatory [cite: 144]
        server_name example.com www.example.com;       # Optional (Virtual Host) [cite: 160]
        root ./www/html;            # Mandatory 
        # root /var/www/html;            # Mandatory 
        # root /tmp;            # Mandatory 
        index index.html;          # Mandatory 
        error_page 404 /404.html;
        error_page 500 /500.html;
        timeout     60;
        # Route for the root directory
        location / {
            client_max_body_size 5G;  
            allowed_methods GET POST;          # Mandatory [cite: 129, 146]
            # index index.html;          # Mandatory 
            index index.1 index.2 index.3 index.4;  # Falls back: index.html → index.htm → 404
            autoindex on;              # Directory listing 
        }

        # Route for file uploads
        location /uploads {
            allowed_methods POST DELETE;       # Allowed allowed_methods [cite: 129, 146]
            upload_store /tmp/uploads; # Upload location [cite: 149]
        }

        # CGI Configuration
        location .php {
            allowed_methods GET POST;
            cgi_ext .py;

            cgi_path ./php-cgi; # CGI execution 
        
        }

        # Redirection example
        location /old-page {
            return 301 /new-page;      # HTTP Redirection 
            error_page 500 501 502 /errors/404.html;   # Mandatory 

        }
        location /cgi-bin {
            root ./www/html;
            cgi_path /usr/bin/python3;  # The "How"
            cgi_ext .py;
            allowed_methods GET POST;
        }
    }

}





