events {
    # Though the subject forces a specific I/O model (single poll/select),
    # you can define max simultaneous connections here for resource management.
    worker_connections 1;
    event_model epoll;
}

http {
    # Global HTTP settings (Inherited by all servers)
    client_max_body_size 1G;          # Mandatory  1G is the max 
    error_page 404 401 402 ./errors/404.html;   # Mandatory 
    
    server {
        listen 127.0.0.1:8080;
        server_name example.com www.example.com;
        root        ./www/html;
        index       index.html;
        timeout     60;
        client_max_body_size 500m;          # Mandatory  1G is the max 

        error_page 404 /errors/404.html;
        error_page 500 /errors/500.html;

        location / {
            client_max_body_size 50m;          # Mandatory  1G is the max 

            allowed_methods GET POST;
            autoindex       off;
            index           index.html;
            return 301 /new-page;      # HTTP Redirection 

        }

        location /cgi-bin/ {
            allowed_methods GET POST;
            cgi_ext   .py;
            cgi_path        /usr/bin/python3;
        }

        location /uploads/ {
            allowed_methods POST;
            client_max_body_size 300m;          # Mandatory  1G is the max 

            upload_path     ./www/uploads/;
        }
    }

}