# Global/Server level
server {

    listen 8080;
    server_name localhost;
    root /var/www/html;
    client_max_body_size 1M;
    error_page 404 /404.html;

    location / {
        # SUBJECT REQUIREMENT: Define accepted methods
        allowed_methods GET; 
        index index.html;
        autoindex on; # SUBJECT REQUIREMENT: Ability to turn on/off directory listing
    }

    location /cgi-bin {
        allowed_methods GET POST;
        cgi_path /usr/bin/python3; # SUBJECT REQUIREMENT: CGI support
        cgi_ext .py;
    }
}

# =========================
# Main Context
# =========================

events {
    worker_connections 1024;
    event_model poll;          # select | poll | epoll
}

http {

    client_max_body_size 1M;

    server {

        listen 0.0.0.0:8080;
        server_name localhost;
        root /var/www/html;
        index index.html;

        location / {
            allowed_methods GET;
            autoindex on;
        }

        location /upload {
            allowed_methods POST;
            upload_store /var/www/uploads;
            client_max_body_size 10M;
        }

        location /cgi-bin {
            allowed_methods GET POST;
            root /var/www/cgi-bin;
            cgi_ext .py;
            cgi_pass /usr/bin/python3;
        }

        error_page 404 /errors/404.html;
    }
}