events {
    worker_connections 1;
    event_model epoll;
}

http {
    client_max_body_size 500M;

    error_page 404 ./www/html/errors/400.html;
    error_page 403 ./www/html/errors/403.html;
    error_page 404 ./www/html/errors/404.html;
    error_page 405 ./www/html/errors/405.html;
    error_page 408 ./www/html/errors/408.html;
    error_page 413 ./www/html/errors/413.html;
    error_page 500 ./www/html/errors/500.html;
    error_page 502 ./www/html/errors/502.html;
    error_page 503 ./www/html/errors/503.html;
    error_page 504 ./www/html/errors/504.html;

    server {
        listen 0.0.0.0:5000;
        server_name fahd.com;

        root ./www/html;
        index index.html;
        timeout 14;
        client_max_body_size 11M;

        location / {
            allowed_methods GET;
            autoindex off;
            index index.html;
        }

        location /dashboard/ {
            allowed_methods GET;
            index index.html;
            autoindex off;
        }

        location /cgi-bin/ {
            allowed_methods GET POST;
            cgi_path /nix/store/sj74dzrygwdxpb54fv7zc6ry75ay4f3n-python-wrapped-0.1.0/bin/python3;
            cgi_ext .py;
        }

        location /redirect/ {
            allowed_methods GET;
            return 301 /new-page.html;
        }

        location /admin/ {
            allowed_methods DELETE;
        }

        location /uploads/ {
            allowed_methods GET POST DELETE;
            upload_store ./www/html/uploads/;
            autoindex on;
        }

        location /errors/ {
            allowed_methods GET;
            autoindex off;
        }
    }
}
