events {
    worker_connections 1;
    event_model epoll;
}

http {
    client_max_body_size 1G;

    server {
        listen 0.0.0.0:5000;
        server_name localhost;
        root        ./www/html;
        index       index.html;
        timeout     60;

        error_page 404 ./www/html/errors/404.html;
        error_page 500 ./www/html/errors/500.html;

        location / {
            allowed_methods GET POST DELETE;
            autoindex       on;
            index           index.html;
        }

        location /cgi-bin {
            root            ./www/html;
            allowed_methods GET POST;
            cgi_ext         .py;
            cgi_path        /nix/store/sj74dzrygwdxpb54fv7zc6ry75ay4f3n-python-wrapped-0.1.0/bin/python3;
        }

        location /uploads {
            allowed_methods POST DELETE GET;
            upload_store    /tmp/uploads;
        }

        location /old-page {
            return 301 /new-page;
        }
    }
}
