#!/usr/bin/env python3
from datetime import datetime

now = datetime.now()
formatted = now.strftime("%A, %d %B %Y %H:%M:%S")

print("Content-Type: text/html")
print()
print(f"""<!DOCTYPE html>
<html lang=\"en\">
<head>
	<meta charset=\"UTF-8\">
	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
	<title>Current Time</title>
	<style>
		body {{
			font-family: 'Segoe UI', Arial, sans-serif;
			background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
			color: #e2e8f0;
			margin: 0;
			padding: 30px;
		}}
		.card {{
			max-width: 600px;
			margin: 10% auto;
			background: #1e293b;
			border-radius: 12px;
			padding: 24px;
			border-left: 4px solid #38bdf8;
			box-shadow: 0 12px 30px rgba(15, 23, 42, 0.4);
		}}
		h1 {{ margin: 0 0 12px 0; color: #7dd3fc; }}
		.time {{ font-size: 18px; font-weight: 600; }}
		a {{ color: #38bdf8; text-decoration: none; }}
		a:hover {{ text-decoration: underline; }}
	</style>
</head>
<body>
	<div class=\"card\">
		<h1>Current Server Time</h1>
		<div class=\"time\">{formatted}</div>
		<p style=\"margin-top:16px; font-size:13px; color:#94a3b8;\">Generated by <code>gettime.py</code></p>
	</div>
</body>
</html>""")
