events {
    worker_connections 1;
    event_model select;
}

http {
    client_max_body_size 1M;
    error_page 404 /errors/404.html;

    server {
        listen 999999;  # invalid port out of range
        root /var/www/html;
    }
}
