events {
    # Duplicate worker_connections should trigger an events duplicate-directive error
    worker_connections 1;
    event_model epoll;
}

http {
    # Invalid size unit and duplicate error_page examples further down
    client_max_body_size 1m;          # Invalid unit (should cause parse error)
    error_page 404 401 402 ./errors/404.html;   # Mandatory 
    
    server {
        server_name example.com www.example.com;
        root        ./www/html;
        index       index.html;
        timeout     60;
        client_max_body_size 500;          # ok

        error_page 404 /errors/404.html;
        error_page 404 /errors/alt_404.html;  # duplicate error code mapping (allowed)

        location / {
            client_max_body_size 50m;          # ok

            allowed_methods GET POST;
            autoindex       off;
            index           index.html;
            return 301 /new-page;      # HTTP Redirection 

        }

        location /cgi-bin/ {
            allowed_methods GET POST;
            cgi_ext   .py;
            cgi_path        /usr/bin/python3;
        }

        location /uploads/ {
            allowed_methods POST;
            upload_path     ./www/uploads/;
        }
    }
}
